# Generated by Django 6.0.1 on 2026-02-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='foto_produto/', verbose_name='Foto Produto (JPG/PNG)'),
        ),
    ]
