# Generated by Django 6.0.1 on 2026-02-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_movimentacao_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='arquivo',
            field=models.ImageField(blank=True, null=True, upload_to='foto_produto/', verbose_name='Foto Produto (JPG/PNG)'),
        ),
    ]
