# Generated by Django 6.0.1 on 2026-02-07 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_movimentacao_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.fornecedor', verbose_name='Fornecedor'),
        ),
    ]
