# Generated by Django 6.0.1 on 2026-02-07 13:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_notafiscal_fornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('descricao', models.CharField(max_length=50, unique=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Função',
                'verbose_name_plural': 'Funções',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('descricao', models.CharField(max_length=50, unique=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Motivo',
                'verbose_name_plural': 'Motivos',
                'ordering': ['descricao'],
            },
        ),
        migrations.AddField(
            model_name='colaborador',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='endereco',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='arquivo',
            field=models.ImageField(blank=True, null=True, upload_to='foto_produto/'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='centro_custo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.centrocusto'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.colaborador'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data_mov',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.fornecedor'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='nota_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.notafiscal'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='observacao_mov',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.produto'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo_mov',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída'), ('A', 'Ajuste')], max_length=1),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.status'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.unidade'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.motivo', verbose_name='Motivo'),
        ),
    ]
