# Generated by Django 6.0.1 on 2026-02-07 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_funcao_motivo_colaborador_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='motivo',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='funcao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.funcao', verbose_name='Função'),
        ),
    ]
