# Generated by Django 6.0.1 on 2026-02-07 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_colaborador_motivo_colaborador_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.motivo'),
        ),
    ]
