# Generated by Django 6.0.1 on 2026-02-13 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_movimentacao_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.centrocusto'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.colaborador'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo_mov',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída'), ('D', 'Devolução')], max_length=1),
        ),
    ]
