# Generated by Django 6.0.1 on 2026-02-19 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_movimentacao_centro_custo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.centrocusto', verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='matricula',
            field=models.IntegerField(default=0, verbose_name='Matrícula'),
        ),
    ]
